name: dns-a-records
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  check-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Check hubelbauer.net DNS A records
        run: ./dns-a-records.sh
