name: dns-a-records
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  check-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Print hubelbauer.net DNS A records
        run: dig hubelbauer.net +noall +answer -t A | grep "^hubelbauer.net"
