name: dns-aaaa-records
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check hubelbauer.net DNS AAAA records
        run: .github/workflows/dns-aaaa-records.sh
      - name: Upload output and pattern artifacts for debugging in case of an error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: |
            output
            pattern
