name: dns-cname-record
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check www.hubelbauer.net DNS CNAME record
        run: .github/workflows/dns-cname-record.sh
      - name: Upload output and pattern artifacts for debugging in case of an error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: |
            output
            pattern
