name: dns-aaaa-records
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check hubelbauer.net DNS AAAA records
        run: .github/workflows/dns-aaaa-records.sh
