name: dns-a-records
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check hubelbauer.net DNS A records
        run: .github/workflows/dns-a-records.sh
