name: https-ssl-certificates
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check hubelbauer.net:443 SSL certificates
        run: .github/workflows/https-ssl-certificates.sh
