name: http-html-document
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check hubelbauer.net:80 HTML document
        run: .github/workflows/http-html-document.sh
