name: hubelbauer.art-aaaa-record
on:
  push:
    paths:
      - .github/workflows/hubelbauer.art-aaaa-record.yml
      - .github/workflows/hubelbauer.art-aaaa-record.sh
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check hubelbauer.art DNS AAAA record
        run: .github/workflows/hubelbauer.art-aaaa-record.sh
      - name: Upload output and pattern artifacts for debugging in case of an error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: |
            output
            pattern
