name: pwd
on: push
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print the current working directory
        run: pwd
      - name: Print tree of the current working directory
        run: tree
