name: tomashubelbauer.com-redirect
on:
  push:
    paths:
      - .github/workflows/tomashubelbauer.com-redirect.yml
      - .github/workflows/tomashubelbauer.com-redirect.sh
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code to get the shell scripts
        uses: actions/checkout@v3
      - name: Check http://tomashubelbauer.com to https://hubelbauer.net redirect
        run: .github/workflows/tomashubelbauer.com-redirect.sh
      - name: Upload output and pattern artifacts for debugging in case of an error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: |
            output
            pattern
